antora:
  extensions:
  - require: '@springio/antora-extensions'
    root_component_name: 'ai'
site:
  title: Spring AI Reference
  url: https://docs.spring.io/spring-ai-mcp/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
  - url: https://github.com/spring-projects-experimental/spring-ai-mcp
    # Refname matching:
    # https://docs.antora.org/antora/latest/playbook/content-refname-matching/
    branches: [main]
    tags: ['v({1..9}).+({0..9}).+({0..9})?(-{RC,M}+({0..9}))']
    start_path: mcp-docs/src/main/antora
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/questions/tagged/spring
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
    stem: 'asciimath'
  extensions:
  - '@asciidoctor/tabs'
  - '@springio/asciidoctor-extensions'
  - '@springio/asciidoctor-extensions/javadoc-extension'
  - '@springio/asciidoctor-extensions/include-code-extension'
  - '@djencks/asciidoctor-mathjax'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  supplemental_files: ./supplemental-ui
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.17/ui-bundle.zip
    snapshot: true
runtime:
  log:
    failure_level: warn
    format: pretty
